version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.10.2
    container_name: elasticsearch-container
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=password
    ports:
      - "9200:9200"
      - "9300:9300"

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"

  nodejs:
    build:
      context: ./node-app
    container_name: nodejs-container
    working_dir: /usr/src/app
    volumes:
      - ./node-app:/usr/src/app
    ports:
      - "3000:3000"